GITHUB_END_POINT="https://api.github.com"
GITHUB_SEARCH_PATH="/search/code"
GRAPH_MULTIPLIER=10
GRAPH_ADDITIVE=10
GRAPH_DEFAULT_COLOR="cyan"
GRAPH_SELECTED_COLOR="red"
GRAPH_HEIGHT=600
GRAPH_WIDTH="100%"