FROM nvidia/cuda:11.1.1-cudnn8-runtime-ubuntu20.04


WORKDIR /app


RUN apt-get update && \
    apt-get install -y python3-pip && \
    pip3 install streamlit torch torchvision

RUN git clone https://github.com/intuit/Trapheus .

cd labs/TrapheusAI

RUN pip3 install -r requirements.txt

EXPOSE 8501

HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health

ENTRYPOINT ["streamlit", "run", "trapheusai_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
